Made a README.md file
Ycandido0119/Tech-Test pull request #1
Opened 2023-12-20 12:55 UTC by Ycandido0119

Added a README file which includes:

 - A brief explanation on what the project is
 - How to setup the project
 - What you need to install for the project
 - How to have it running on your local browser

2023-12-20 13:53 UTC, todaatsushi requested changes
Good start but the steps are broken. It's *very* common to have many PR comments as you are starting out - these aren't critiques, but people collabing on trying to get this change live. If you need to clarify, you should either reach out directly or respond to comments.

> It might be beneficial to periodically follow these steps yourself in another directory to test that your instructions work.

I'd follow this advice from the ticket.

2023-12-20 13:53 UTC, todaatsushi commented on README.md
> +source mysite/bin.activate
This command doesn't work for me - is there a typo?

2023-12-20 13:53 UTC, todaatsushi commented on README.md
> +source mysite/bin.activate
Similarly, it looks like something has gone wrong here with sourcing this - it doesn't seem to use it when I run it. Let's pair on this later.

2023-12-20 13:53 UTC, todaatsushi commented on README.md
> +4.2.5
I'm getting `5.0` 🤔 perhaps this is because this is the latest version?

2023-12-20 13:53 UTC, todaatsushi commented on README.md
> +To get into the admin site once you have ran that command enter the browser window, add the admin url in the address bar.
Worth noting which URL this is.

2023-12-20 13:53 UTC, todaatsushi commented on README.md
> +When running the Django project make sure you are in the local environment. Navigate to the "octoapp" folder and execute this command in the command prompt:
Worth letting the user know where this is

2023-12-20 13:53 UTC, todaatsushi commented on README.md
> +To get into the admin site once you have ran that command enter the browser window, add the admin url in the address bar.
Also, i'm seeing

![Screenshot 2023-12-20 at 13 47 04](https://github.com/Ycandido0119/Tech-Test/assets/28542196/50438e67-9726-459b-926b-94b47d34b459)

2023-12-20 13:53 UTC, todaatsushi commented on README.md
> +After you must enter: username, email address and a password.
This doesn't feel like the end of the app for me - for example, the aim of the app is to import d0010 files, and there isn't any info to say how to do that

2023-12-20 13:53 UTC, todaatsushi commented on README.md
> +This is a Django web application for storing files.
Is it? IIRC the spec has a lot more detail than this on what the app is meant to do.

2023-12-20 15:23 UTC, Ycandido0119 commented on README.md
> +4.2.5
I tested on my command prompt and I got 4.2.5, I think its because maybe my Django is outdated.

2024-01-08 10:42 UTC, todaatsushi requested changes

2024-01-08 10:42 UTC, todaatsushi commented on README.md
> +This is a Django web application for storing files.
The initial doc outlining the task should help with this.

2024-01-08 10:42 UTC, todaatsushi commented on README.md
> +python -m pip install django
This can just be `pip install django` btw. Also, as we discussed, there will be a way to specify the version required so line 57 is consistent with everyone.

2024-01-08 10:42 UTC, todaatsushi commented on README.md
> +Now you need to import the files into the datab
typo?

2024-01-09 09:23 UTC, todaatsushi approved these changes

2024-01-09 09:24 UTC, merged