Rename octoapp to src
Ycandido0119/Tech-Test pull request #11
Opened 2024-02-21 14:53 UTC by Ycandido0119

### Asana Ticket

_NA_

### PR Description

_Rename octoapp directory to src_

### Checklist

[ ] Went through and checked that I haven't commited anything I shouldn't.
[ ] I have gone over the commit with a mentor.
[ ] I have understood the logic of the ticket and if not wrote questions on things I am stuck on.

2024-02-21 15:29 UTC, todaatsushi reviewed
As long as everything works, this looks good - do the tests pass / app functionality still work?

Only note is the README will need updating

2024-02-21 15:29 UTC, todaatsushi commented on src/challenges/management/commands/my_custom_command.py
> +                        print(dictionary)
Could remove these `print` calls while we're here 👀

2024-02-21 15:29 UTC, todaatsushi commented on src/challenges/management/commands/my_custom_command.py
> +                        print(dictionary)
♻️

2024-02-21 15:29 UTC, todaatsushi commented on src/challenges/management/commands/my_custom_command.py
> +                        print(dictionary)
♻️

2024-02-23 11:56 UTC, todaatsushi requested changes

2024-02-23 11:56 UTC, todaatsushi commented on README.md
> +source .venv/bin/activate
This name doesn't match the env name above - this name is the more correct one as `.env` is a commonly used filename for holding sensitive vars.

2024-02-23 11:57 UTC, Ycandido0119 commented on README.md
> +source .venv/bin/activate
Okay am changing the on at the top to .venv

2024-02-23 12:02 UTC, todaatsushi approved these changes

2024-02-23 12:19 UTC, merged