Implement delete method for a reading in the models.
Ycandido0119/Tech-Test pull request #15
Opened 2024-03-05 10:13 UTC by Ycandido0119

### Asana Ticket

_Add delete method to models_

### PR Description

 - Implement a delete method for each of the models in `models.py`
 - Make edits to `admins.py`
 - Write up tests to check if readings would be deleted
 - Create a new file to store tests made regarding models

### Checklist

- [ x ] Went through and checked that I haven't commited anything I shouldn't.
- [ x ] I have gone over the commit with a mentor.
- [ x ] All tests are passing
- [ x ] I've manually verified the acceptance criteria is met
- [ x ] Any relevant documentation is updated

2024-03-05 10:17 UTC, AlexMc124 commented on src/tests/test_view.py
> +@pytest.mark.django_db
These are added in the `test_models` file and should be removed from here.

2024-03-05 10:18 UTC, AlexMc124 commented on src/tests/test_models.py
> +@pytest.fixture
This isn't used please remove this!

2024-03-05 10:18 UTC, AlexMc124 commented on src/tests/test_models.py
> +@pytest.mark.django_db
♻️

2024-03-05 10:18 UTC, AlexMc124 commented on src/tests/test_models.py
> +@pytest.mark.django_db
♻️ Spacing

2024-03-05 10:19 UTC, AlexMc124 commented on src/challenges/models.py
> +# @property
This needs to be removed

2024-03-05 10:49 UTC, todaatsushi requested changes

2024-03-05 10:49 UTC, todaatsushi commented on src/challenges/models.py
> +#        return self.meter.serial_number
🌚

2024-03-05 11:13 UTC, chloe-umble commented
❓ Would you mind linking the asana ticket in the description? Sometimes tickets are across projects or boards that not all reviewers have easily on hand, so making it an easy 1-click away is a good way to give them more context on the requirements, scope of the work, or provide more detail on how this unit of work fits into a broader objective.

2024-03-06 09:41 UTC, todaatsushi commented on src/challenges/admin.py
> +    search_fields = []
Is this change on purpose? This would be editing current functionality *without* it being addressed in commits or (explicitly) in the PR description.

2024-03-06 09:41 UTC, todaatsushi commented on src/tests/test_models.py
> +    def test_soft_deleted_meterpoint_not_in_model(self):
❓ What does it mean by `not_in_model`?

If we're testing that the `delete` method doesn't affect the object *before* you refresh from the db, the change is unrelated to these changes, and more a function of how objects are queried from the database.

That behaviour is something else entirely, and built in to how any query to an external data source would work. 

It's probably not a required suite of tests. 

The tests I'd expect to see for this feature would be:
- Does deleting a meterpoint set all related things downwards to deleted?
- Does deleting a meter set all related things downwards to deleted?
- Does deleing a register delete all readings?
- Does filtering for active on any of these models remove these entries from the queryset?

And by delete, we want to confirm that the field is True.

2024-03-06 17:12 UTC, todaatsushi approved these changes
Very nice. It looks good.

Minor comments, so please merge after those are addressed (i'm pre-approving as they're small).

One last point. It's almost always a good idea to include data migrations separately to business logic changes. Not a huge deal now so more of an FYI.

2024-03-06 17:12 UTC, todaatsushi commented on src/tests/test_models.py
> +        )
Maybe create an unrelated one & assert that isn't deleted?

2024-03-06 17:13 UTC, merged