Created a .env file
Ycandido0119/Tech-Test pull request #2
Opened 2024-01-15 14:23 UTC by Ycandido0119

- Created a .env file and added two environment variables
 - In the settings.py implement a way to inject the environment variables
 - Update the README file to explain how the user needs to setup the application

2024-01-15 15:50 UTC, todaatsushi requested changes

2024-01-15 15:50 UTC, todaatsushi commented on .vscode/launch.json
> +}
Did you mean to add this to the branch?

2024-01-15 15:50 UTC, todaatsushi commented on mysite/octoapp/octoapp/settings.py
> +print(os.environ.get("TECH_TEST_SECRET_KEY"))
Do you want this to run?

2024-01-15 16:11 UTC, Ycandido0119 commented on mysite/octoapp/octoapp/settings.py
> +print(os.environ.get("TECH_TEST_SECRET_KEY"))
No I realised now and I am making further changes also in the README file as well.

2024-01-16 09:28 UTC, todaatsushi approved these changes

2024-01-16 11:23 UTC, merged