Implement a list view that shows all the entries
Ycandido0119/Tech-Test pull request #8
Opened 2024-01-31 15:23 UTC by Ycandido0119

### Asana Ticket

Implement a list view that shows all the entries

### PR Description

 - Created a templete folder and inside a html file in order to display my meterpoint data
 - Amended the views.py file 
 - Did some debugging for the custom command to ensure it works

### Checklist

[ x ] Went through and checked that I haven't commited anything I shouldn't.
[ x ] I have gone over the commit with a mentor.
[ x ] I have understood the logic of the ticket and if not wrote questions on things I am stuck on.

2024-02-06 16:32 UTC, todaatsushi requested changes
A very good start. It looks like it should work, and having tests is always great!

I'd think about the written communication side of the PR. For example, the description and commits don't allude to any of the changes around the management command, or setting up pytest.

These should be addressed (as one of the comments say). The other option is to split up the pull request so it does one thematic thing (e.g. set up pytest, fix the command, or change the model). This way, it's very easy to see what's happening and the key to getting quicker reviews!

2024-02-06 16:32 UTC, todaatsushi commented on octoapp/challenges/management/commands/my_custom_command.py
> -                        )
It's not clear to me why we are changing the management command - could we add more detail in any of the following:
- Description of the PR
- Comments (preceeded with 🍷 🧀 )
- Commit messages

More detail: https://github.com/octoenergy/coding-conventions/blob/master/conventions/pull-requests.md#ensure-your-reviewers-have-enough-context

2024-02-06 16:32 UTC, todaatsushi commented on octoapp/challenges/templates/meterpoint.html
> +</html>
🐼 is formatting available for html?

2024-02-06 16:32 UTC, todaatsushi commented on octoapp/challenges/urls.py
> +    path("meterpoint", views.meterpoint, name="meterpoint"),
Are these names accurate? Is this to view a meterpoint?

2024-02-06 16:32 UTC, todaatsushi commented on octoapp/challenges/views.py
> +    readings = Reading.objects.count()
These two variables `meters` and `readings` imply the data, but the right hand side is only providing the counts - could we improve the variable names?

2024-02-06 16:32 UTC, todaatsushi commented on octoapp/challenges/views.py
> +    print(sort_by)
🌚

2024-02-06 16:32 UTC, todaatsushi commented on octoapp/challenges/templates/meterpoint.html
> +</html>
Name of the template doesn't quite match again - is this a single meterpoint or multiple?

2024-02-06 16:32 UTC, todaatsushi commented on octoapp/challenges/views.py
> +    filename = Reading.objects.first().flow_filename
`first()` can also return `None` - which happens when there are no models in your db. In that case, this will raise an error, as `None` doesn't have a `flow_filename`. You'll need to guard against this in this code.

2024-02-06 16:32 UTC, todaatsushi commented on octoapp/challenges/views.py
> +        meterpoints = meterpoints.order_by("mpan")
This is very nice, it's really common for people to assume user inputs come in in certain formats. Very good idea to standardise it.

2024-02-06 16:32 UTC, todaatsushi commented on octoapp/challenges/views.py
> +    sort_by = request.GET.get("sort_by", "")
🐼 let's make sure we're using the same language all over ie. `sort` vs `order`

2024-02-06 16:32 UTC, todaatsushi commented on octoapp/tests/test_view.py
> +# Create your tests here.
🐼 can probably remove this!

2024-02-06 16:32 UTC, todaatsushi commented on octoapp/tests/test_view.py
> +    assert response.context["filename"] == reading.flow_filename
Let's introduce some spacing in the code here - it's much easier to infer intent with the more subtle hints like spacing between code blocks.

For example, spacing between creating of models, and other things in the `Arrange` step - have a think about what it is written down. Which lines conceptually live together etc. Remember that the person reading this won't know as much as you.

2024-02-12 15:28 UTC, todaatsushi reviewed
Almost there - looking very good.

2024-02-12 15:28 UTC, todaatsushi commented on octoapp/challenges/views.py
> +        filename ="No readings exists"
This isn't a valid filename - what is this trying to show? Could you refactor the code to better house this data?

Also, it seems like this view is assuming that only one file can exist (ie. all readings were uploaded in one file). Either that or there is a bug in the logic here. This shouldn't be the case!

2024-02-12 15:28 UTC, todaatsushi commented on octoapp/tests/test_view.py
> +    assert response.context["filename"] == reading.flow_filename
This is well spaced and much easier to read 👍

2024-02-12 15:32 UTC, Ycandido0119 commented on octoapp/challenges/views.py
> +        filename ="No readings exists"
So instead of just filename we need to be specific, since we are looking for the flow_filename in readings, something like readings_filename?

2024-02-13 13:23 UTC, merged